### ISSUE TITLE
Need to know prereqs for nginx_install_controller.yml

### ISSUE THREAD

**Issue by janibashamd** [brianehlert/ansible-nginx-controller-examples#5]
Hi,

I am trying to use nginx_install_controller.yml file. WE have to update vars in nginx_install_controller_vars.yml but in dilemma if we have to install database before running this yml file as i see line 6-9 are asking about db details.

TIA

**Comment by aknot242** [comment]
Do you intend to create your own external Postgres installation, or do you want the controller installer to create its own instance?

**Comment by brianehlert** [comment]
To expand a bit:
Historically NGINX Controller required an external instance of PostgreSQL for the configuration database.  You were responsible for managing this.
Back in December 2020 this changed, and NGINX Controller now supports an internal instance of PostgreSQL.  The NGINX Controller system manages this.

Today, we recommend using the internal database, unless you have a compelling reason to manage your own instance of PostgreSQL.

If you are setting up a production installation, we recommend using an external NFS share to host both the configuration and timeseries databases.

This is why there are so many database related options.

**Comment by janibashamd** [comment]
thanks for the update and can you check this issue as well - https://github.com/nginxinc/ansible-role-nginx-controller-install/issues/16

they are different repos so raised it there.

**Comment by janibashamd** [comment]
With assistance from Daniel able to bring up controller using below files -

Requirement - Need to deploy NGINX controller with local database configuration
Prerequisites-
1. Docker installed on EC2 machine
2. Controller tar file already available in /home/ubuntu of same EC2 instance
3. My nginx collection file and install them using cmd - 
`ansible-galaxy install -r ./collections/requirements.yml --force`
`---
collections:
  - name: nginxinc.nginx_controller
    version: 3.8.0
`

vars file -
`---
su_password: 'adm....'
nginx_controller_tarball: "/home/ubuntu/{{controller_tarball}}"
nginx_controller_install_path: /home/ubuntu
nginx_controller_remote_source: "true"
nginx_controller_tsdb_volume_type: "local"
nginx_controller_smtp_host: "localhost"
nginx_controller_smtp_port: "25"
nginx_controller_smtp_authentication: "false"
nginx_controller_smtp_use_tls: false
nginx_controller_noreply_address: "nore,,.....test"
nginx_controller_fqdn: ""
nginx_controller_organization_name: "apisec"
nginx_controller_admin_firstname: "apisec"
nginx_controller_admin_lastname: "admin"
nginx_controller_admin_email: "admin@..."
nginx_controller_user_email: "admin@...."
nginx_controller_user_password: 'Test....'
nginx_controller_admin_password: 'Test.....'
nginx_controller_self_signed_cert: true
nginx_controller_overwrite_existing_configs: true
nginx_controller_auto_install_docker: false
nginx_controller_bundled_db: true
controller_tarball: "controller-installer.tar.gz"

ansible_python_interpreter: /usr/bin/python3
`
Note: i have removed my usr/pwd credentials

Below is my playbook -
`---
## retreive dynamic settings information at the Ansible Controller

## on the remote host
- name: load vars and prereqs
  hosts: f5_test
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
  - name: load the vars
    include_vars: 
      file: "{{playbook_dir}}/nginx_install_controller_vars.yaml"

  - name:  make sure all the prerequisites are present
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - gettext
      - bash
      - gzip
      - coreutils
      - grep
      - less
      - sed
      - tar
      - jq
      - socat
      - conntrack
      - ebtables
      - python-pexpect  # to support ansible
    tags: packages

  # Supporting su requirement for Controller installer role
  - name: set root password to support su for Controller installation with Ubuntu
    user:
      name: root
      password: "{{ su_password | password_hash('sha512') }}"


## changing security context on the remote host to su
- name: install controller
  remote_user: ubuntu
  hosts: f5_test
  become: yes
  become_user: ubuntu
  become_method: su
  gather_facts: false
  collections:
  - nginxinc.nginx_controller

  pre_tasks:
  - name: load the vars
    include_vars: 
      file: "{{playbook_dir}}/nginx_install_controller_vars.yaml"

  - name: set the controller public fqdn variable
    set_fact:
      nginx_controller_fqdn: "{{nginx_controller_fqdn}}"

  tasks:
    - name: Print some db debug information 
      debug: msg="Hello your DB details are - {{nginx_controller_bundled_db}}, {{nginx_controller_db_host}}, {{nginx_controller_configdb_volume_type}}"
      
    - name: initiate controller install role
      import_role:
        name: nginx_controller_install


# pull the install log
- hosts: controller
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
  - name: fetch the install log
    fetch:
      src: /var/log/nginx-controller/nginx-controller-install.log
      dest: "{{playbook_dir}}/logs/"
`
Below is my commad used:
`ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u ubuntu -i controller -e "nginx_controller_fqdn=<IP>" --private-key $TF_VAR_ec2_key_name nginx_install_controller.yaml
      `

Challenges faced: 

1. "ebtables" package was missing in repo examples so installation was failing. Added it in required packages section of playbook and issue is fixed
2. Even though installation was complete ansible execution failed because of ssh timeouts.

**Comment by janibashamd** [comment]
Because of some special chars all messages coming in incorrect lines and fonts..

**Comment by janibashamd** [comment]
Attached some example in another PR to deploy controller in embedded mode so closing this issue.
